[server]
port = 5565

[node]
detect-drivers = false

[relay]
url = "http://appium2:4733"
status-endpoint = "/status"
configs = [
  "1", "{\"platformName\":\"Android\",\"appium:automationName\":\"UiAutomator2\"}"
]
