# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.3.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/agent1: d8ae7c169380345586c3e83abd57d7667d257de6c73ba61bab5240fe98a262f7
    io.kubernetes.cri-o.SandboxID/jenkins: d8ae7c169380345586c3e83abd57d7667d257de6c73ba61bab5240fe98a262f7
  creationTimestamp: "2025-02-27T15:34:09Z"
  labels:
    app: pjenkins
  name: pjenkins
spec:
  containers:
  - image: docker.io/jenkins/jenkins:latest
    name: jenkins
    securityContext: {}
    volumeMounts:
    - mountPath: /var/jenkins_home
      name: jenkins_home-pvc
  - args:
    - -url
    - http://jenkins:8080
    - -secret
    - 7ebc52972d0f9cbaa1798790af11a8fe891bd47a04ffdd675d2d3d83cd5b3ae4
    - -name
    - Agent1
    image: docker.io/jenkins/inbound-agent:latest
    name: agent1
    securityContext: {}
    volumeMounts:
    - mountPath: /home/jenkins/agent
      name: d777cc5e7abd6dd92e195835778e8267845f3de89fb96809f23e689b9cd192da-pvc
    - mountPath: /home/jenkins/.jenkins
      name: bcb14708e3102e7b6b0787f405a63ebf6484114327b4185ce9a17f3a73af3c44-pvc
  volumes:
  - name: jenkins_home-pvc
    persistentVolumeClaim:
      claimName: jenkins_home
  - name: d777cc5e7abd6dd92e195835778e8267845f3de89fb96809f23e689b9cd192da-pvc
    persistentVolumeClaim:
      claimName: d777cc5e7abd6dd92e195835778e8267845f3de89fb96809f23e689b9cd192da
  - name: bcb14708e3102e7b6b0787f405a63ebf6484114327b4185ce9a17f3a73af3c44-pvc
    persistentVolumeClaim:
      claimName: bcb14708e3102e7b6b0787f405a63ebf6484114327b4185ce9a17f3a73af3c44
