[server]
host = "appium-relay-2"
port = 5565

[node]
detect-drivers = false

[relay]
url = "http://appium2:4733"
status-endpoint = "/status"
configs = [
  "1", "{\"platformName\":\"Android\",\"appium:automationName\":\"UiAutomator2\"}"
]

[events]
host ="selenium-hub"
publish = "tcp://selenium-hub:4442"
subscribe = "tcp://selenium-hub:4443"
